# Generated by Django 5.1.4 on 2025-01-20 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Título"
                    ),
                ),
                ("contenido", models.TextField(null=True, verbose_name="Contenido")),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="entradas/%Y/%m/%d", verbose_name="Immagen"
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.categoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
                "db_table": "entradas",
                "ordering": ["id"],
            },
        ),
    ]
