# Generated by Django 5.1.4 on 2025-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrada",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="entradas/%Y/%m/%d",
                verbose_name="Imagen",
            ),
        ),
    ]
